#define LCD_PIN_ELETRO 0x46
#define LCD_PIN_MEC 0x45
#define LCD_PIN_PGN 0x44
#define LCD_PIN_METAL 0x43

#define LED_PIN_ELETRO 13
#define LED_PIN_MEC 12
#define LED_PIN_PGN 11
#define LED_PIN_METAL 10

#define BUTTON_PIN_ELETRO 7
#define BUTTON_PIN_MEC 6
#define BUTTON_PIN_PGN 5
#define BUTTON_PIN_METAL 4

#define INFRARED_PIN 3