[project]
name = "ENGF93"
version = "0.1.0"
requires-python = "==3.14.6"
dependencies = [
    "control>=0.10.2",
    "hickle>=5.0.3",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.0",
    "numpy>=2.4.6",
    "scipy>=1.18.0",
    "sympy>=1.14.0",
]

[dependency-groups]
dev = ["ruff>=0.15.18"]

[tool.ruff.lint]
extend-select = ["I", "NPY", "FLY", "UP"]
ignore = ["E741"]
